version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - NODE_ENV=staging
      - API_URL=http://backend:5001
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - FLASK_APP=server.py
      - FLASK_ENV=staging
      - PYTHONUNBUFFERED=1
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge 