version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - NODE_ENV=production
      - API_URL=http://backend:5001
    restart: always
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  backend:
    build: ./backend
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - FLASK_APP=server.py
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    networks:
      - app-network
    restart: always
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  app-network:
    driver: bridge 